#! /bin/bash

sudo cp /home/peix/hashpipe/uwb_hashpipe/*.sh /usr/local/bin/
  
#for i in uwb-gpu1 uwb-gpu2       # Nanshan
#do
#echo ssh -p 5907 $i sudo cp /home/peix/hashpipe/uwb_hashpipe/*.sh /usr/local/bin/
#
#ssh -p 5907 $i sudo cp /home/peix/hashpipe/uwb_hashpipe/*.sh /usr/local/bin/
#
#done
